ti-am335x: define SUPPORT_X11 for CXXFLAGS to fix webtikgtk build error
Issue: LIN1018-3094

for ti-am335x machine, when distro feature x11 is enabled, there is an
issue as follows:

DerivedSources/WebCore/unified-sources/UnifiedSource347.cpp:2:
WebCore/platform/graphics/egl/GLContextEGLX11.cpp: In static member function 'static void* WebCore::GLContextEGL::createWindowSurfaceX11(EGLDisplay, EGLConfig, GLNativeWindowType)':
WebCore/platform/graphics/egl/GLContextEGLX11.cpp:42:91: error: invalid static_cast from type 'GLNativeWindowType' {aka 'long long unsigned int'} to type 'EGLNativeWindowType' {aka       'void*'}
    return eglCreateWindowSurface(display, config, static_cast<EGLNativeWindowType>(window), nullptr);

This patch is to define SUPPORT_X11 to avoid this conflict.

Signed-off-by: Zumeng Chen <zumeng.chen@windriver.com>