ti-am335x: fix a insane check when build other bsps
Issue: CGP9-287

This patch is to fix QA issues from binary arch-check because of linux-firmware,
so remove ti-am335x limitation to cater for 'bitbake world'

ERROR: linux-firmware-1_0.0+gitAUTOINC+42ad5367dd-r0 do_package_qa: QA Issue: linux-firmware: Recipe inherits the allarch class, but has packaged architecture-specific binaries
linux-firmware: Recipe inherits the allarch class, but has packaged architecture-specific binaries
linux-firmware: Recipe inherits the allarch class, but has packaged architecture-specific binaries
linux-firmware: Recipe inherits the allarch class, but has packaged architecture-specific binaries
linux-firmware: Recipe inherits the allarch class, but has packaged architecture-specific binaries
linux-firmware: Recipe inherits the allarch class, but has packaged architecture-specific binaries
linux-firmware: Recipe inherits the allarch class, but has packaged architecture-specific binaries
linux-firmware: Recipe inherits the allarch class, but has packaged architecture-specific binaries [arch]
ERROR: linux-firmware-1_0.0+gitAUTOINC+42ad5367dd-r0 do_package_qa: QA run found fatal errors. Please consider fixing them.
ERROR: linux-firmware-1_0.0+gitAUTOINC+42ad5367dd-r0 do_package_qa: Function failed: do_package_qa

Signed-off-by: Zumeng Chen <zumeng.chen@windriver.com>