eglinfo-x11: Added bbappend to define SUPPORT_X11 for CXXFLAGS of ti-am335x
Issue: LIN10-4968

for ti-am335x machine, when distro feature x11 is enabled, there is
below issue:
../../src/platform_x11_generic.cpp:109:38: error: invalid conversion
from 'Display* {aka _XDisplay*}' to 'EGLNativeDisplayType {aka int}'
[-fpermissive]
m_egl_native_display = XOpenDisplay(p_name);

The reason is that eglinfo-x11 includes the header file 'EGL/eglplatform.h'
from 'ti-sgx-ddk-um' and this header file needs 'SUPPORT_X11' to be defined
for UNIX platform with 'x11'.

Signed-off-by: Haiqing Bai <Haiqing.Bai@windriver.com>