ti-am335x: add gpu dependency to gpudriver setting
Issue: LIN1023-3140 LIN1023-3150

gpudriver depends on the gpu feature, so add the gpu feature
judgment for gpudriver, to avoid below building issue if gpu
is not enabled.
ERROR: Nothing PROVIDES 'virtual/libgles2' (but layers/oe-core/meta/recipes-graphics/cairo/cairo_1.16.0.bb DEPENDS on or otherwise requires it). Close matches:
virtual/libc
virtual/libsdl2
virtual/libusb0
ERROR: Required build target 'lmsensors' has no buildable providers.
Missing or unbuildable dependency chain was: ['lmsensors', 'rrdtool', 'cairo', 'virtual/libgles2']

Signed-off-by: Xulin Sun <xulin.sun@windriver.com>