libgbm: add virtual/libgbm to PROVIDES
Issue: LIN1018-3094

Both mesa and libgbm provide the libgbm
functionality and there comes some conflict
as below:
ERROR: The recipe libgbm is trying to install files into a shared area when those files already exist. Those files and their manifest location are:
  /home/wrlbuild/builds/builds-78bbcb82-34fb-4599-85b6-03ac5bb7bd58/wrlinux_qemuarm_std-sato_faw_alldistro_predefined_18-lts/tmp-glibc/pkgdata/qemuarm/runtime/libgbm
    (matched in manifest-qemuarm-mesa.packagedata)
  /home/wrlbuild/builds/builds-78bbcb82-34fb-4599-85b6-03ac5bb7bd58/wrlinux_qemuarm_std-sato_faw_alldistro_predefined_18-lts/tmp-glibc/pkgdata/qemuarm/runtime/libgbm-dev.packaged
    (matched in manifest-qemuarm-mesa.packagedata)
  /home/wrlbuild/builds/builds-78bbcb82-34fb-4599-85b6-03ac5bb7bd58/wrlinux_qemuarm_std-sato_faw_alldistro_predefined_18-lts/tmp-glibc/pkgdata/qemuarm/runtime/libgbm-dev
    (matched in manifest-qemuarm-mesa.packagedata)
  /home/wrlbuild/builds/builds-78bbcb82-34fb-4599-85b6-03ac5bb7bd58/wrlinux_qemuarm_std-sato_faw_alldistro_predefined_18-lts/tmp-glibc/pkgdata/qemuarm/runtime/libgbm.packaged
    (matched in manifest-qemuarm-mesa.packagedata)
  /home/wrlbuild/builds/builds-78bbcb82-34fb-4599-85b6-03ac5bb7bd58/wrlinux_qemuarm_std-sato_faw_alldistro_predefined_18-lts/tmp-glibc/pkgdata/qemuarm/shlibs2/libgbm.list
    (matched in manifest-qemuarm-mesa.packagedata)
  /home/wrlbuild/builds/builds-78bbcb82-34fb-4599-85b6-03ac5bb7bd58/wrlinux_qemuarm_std-sato_faw_alldistro_predefined_18-lts/tmp-glibc/pkgdata/qemuarm/shlibs2/libgbm-dev.pclist
    (matched in manifest-qemuarm-mesa.packagedata)
Please verify which recipe should provide the above files.

So add virtual target for libgbm and then can
use PREFERRED_PROVIDER mechanism to resolve this
kind of conflict as above.

Signed-off-by: Mingli Yu <Mingli.Yu@windriver.com>